/*
 * Generated by gdbus-codegen 2.32.3. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "gum-dbus-group-gen.h"

#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        ret = (g_value_get_double (a) == g_value_get_double (b));
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.tizen.SecurityAccounts.gUserManagement.Group
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:GumDbusGroup
 * @title: GumDbusGroup
 * @short_description: Generated C code for the org.tizen.SecurityAccounts.gUserManagement.Group D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-tizen-SecurityAccounts-gUserManagement-Group.top_of_page">org.tizen.SecurityAccounts.gUserManagement.Group</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.tizen.SecurityAccounts.gUserManagement.Group ---- */

static const _ExtendedGDBusArgInfo _gum_dbus_group_method_info_add_group_IN_ARG_preferred_gid =
{
  {
    -1,
    "preferred_gid",
    "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _gum_dbus_group_method_info_add_group_IN_ARG_pointers[] =
{
  &_gum_dbus_group_method_info_add_group_IN_ARG_preferred_gid,
  NULL
};

static const _ExtendedGDBusArgInfo _gum_dbus_group_method_info_add_group_OUT_ARG_gid =
{
  {
    -1,
    "gid",
    "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _gum_dbus_group_method_info_add_group_OUT_ARG_pointers[] =
{
  &_gum_dbus_group_method_info_add_group_OUT_ARG_gid,
  NULL
};

static const _ExtendedGDBusMethodInfo _gum_dbus_group_method_info_add_group =
{
  {
    -1,
    "addGroup",
    (GDBusArgInfo **) &_gum_dbus_group_method_info_add_group_IN_ARG_pointers,
    (GDBusArgInfo **) &_gum_dbus_group_method_info_add_group_OUT_ARG_pointers,
    NULL
  },
  "handle-add-group",
  FALSE
};

static const _ExtendedGDBusMethodInfo _gum_dbus_group_method_info_delete_group =
{
  {
    -1,
    "deleteGroup",
    NULL,
    NULL,
    NULL
  },
  "handle-delete-group",
  FALSE
};

static const _ExtendedGDBusMethodInfo _gum_dbus_group_method_info_update_group =
{
  {
    -1,
    "updateGroup",
    NULL,
    NULL,
    NULL
  },
  "handle-update-group",
  FALSE
};

static const _ExtendedGDBusArgInfo _gum_dbus_group_method_info_add_member_IN_ARG_uid =
{
  {
    -1,
    "uid",
    "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _gum_dbus_group_method_info_add_member_IN_ARG_add_as_admin =
{
  {
    -1,
    "add_as_admin",
    "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _gum_dbus_group_method_info_add_member_IN_ARG_pointers[] =
{
  &_gum_dbus_group_method_info_add_member_IN_ARG_uid,
  &_gum_dbus_group_method_info_add_member_IN_ARG_add_as_admin,
  NULL
};

static const _ExtendedGDBusMethodInfo _gum_dbus_group_method_info_add_member =
{
  {
    -1,
    "addMember",
    (GDBusArgInfo **) &_gum_dbus_group_method_info_add_member_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-add-member",
  FALSE
};

static const _ExtendedGDBusArgInfo _gum_dbus_group_method_info_delete_member_IN_ARG_uid =
{
  {
    -1,
    "uid",
    "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _gum_dbus_group_method_info_delete_member_IN_ARG_pointers[] =
{
  &_gum_dbus_group_method_info_delete_member_IN_ARG_uid,
  NULL
};

static const _ExtendedGDBusMethodInfo _gum_dbus_group_method_info_delete_member =
{
  {
    -1,
    "deleteMember",
    (GDBusArgInfo **) &_gum_dbus_group_method_info_delete_member_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-delete-member",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _gum_dbus_group_method_info_pointers[] =
{
  &_gum_dbus_group_method_info_add_group,
  &_gum_dbus_group_method_info_delete_group,
  &_gum_dbus_group_method_info_update_group,
  &_gum_dbus_group_method_info_add_member,
  &_gum_dbus_group_method_info_delete_member,
  NULL
};

static const _ExtendedGDBusSignalInfo _gum_dbus_group_signal_info_unregistered =
{
  {
    -1,
    "unregistered",
    NULL,
    NULL
  },
  "unregistered"
};

static const _ExtendedGDBusSignalInfo * const _gum_dbus_group_signal_info_pointers[] =
{
  &_gum_dbus_group_signal_info_unregistered,
  NULL
};

static const _ExtendedGDBusPropertyInfo _gum_dbus_group_property_info_grouptype =
{
  {
    -1,
    "grouptype",
    "q",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE,
    NULL
  },
  "grouptype",
  FALSE
};

static const _ExtendedGDBusPropertyInfo _gum_dbus_group_property_info_gid =
{
  {
    -1,
    "gid",
    "u",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "gid",
  FALSE
};

static const _ExtendedGDBusPropertyInfo _gum_dbus_group_property_info_groupname =
{
  {
    -1,
    "groupname",
    "s",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE,
    NULL
  },
  "groupname",
  FALSE
};

static const _ExtendedGDBusPropertyInfo _gum_dbus_group_property_info_secret =
{
  {
    -1,
    "secret",
    "s",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE,
    NULL
  },
  "secret",
  FALSE
};

static const _ExtendedGDBusPropertyInfo * const _gum_dbus_group_property_info_pointers[] =
{
  &_gum_dbus_group_property_info_grouptype,
  &_gum_dbus_group_property_info_gid,
  &_gum_dbus_group_property_info_groupname,
  &_gum_dbus_group_property_info_secret,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _gum_dbus_group_interface_info =
{
  {
    -1,
    "org.tizen.SecurityAccounts.gUserManagement.Group",
    (GDBusMethodInfo **) &_gum_dbus_group_method_info_pointers,
    (GDBusSignalInfo **) &_gum_dbus_group_signal_info_pointers,
    (GDBusPropertyInfo **) &_gum_dbus_group_property_info_pointers,
    NULL
  },
  "group",
};


/**
 * gum_dbus_group_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-tizen-SecurityAccounts-gUserManagement-Group.top_of_page">org.tizen.SecurityAccounts.gUserManagement.Group</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
gum_dbus_group_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_gum_dbus_group_interface_info;
}

/**
 * gum_dbus_group_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #GumDbusGroup interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
gum_dbus_group_override_properties (GObjectClass *klass, guint property_id_begin)
{
  g_object_class_override_property (klass, property_id_begin++, "grouptype");
  g_object_class_override_property (klass, property_id_begin++, "gid");
  g_object_class_override_property (klass, property_id_begin++, "groupname");
  g_object_class_override_property (klass, property_id_begin++, "secret");
  return property_id_begin - 1;
}



/**
 * GumDbusGroup:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-tizen-SecurityAccounts-gUserManagement-Group.top_of_page">org.tizen.SecurityAccounts.gUserManagement.Group</link>.
 */

/**
 * GumDbusGroupIface:
 * @parent_iface: The parent interface.
 * @handle_add_group: Handler for the #GumDbusGroup::handle-add-group signal.
 * @handle_add_member: Handler for the #GumDbusGroup::handle-add-member signal.
 * @handle_delete_group: Handler for the #GumDbusGroup::handle-delete-group signal.
 * @handle_delete_member: Handler for the #GumDbusGroup::handle-delete-member signal.
 * @handle_update_group: Handler for the #GumDbusGroup::handle-update-group signal.
 * @get_gid: Getter for the #GumDbusGroup:gid property.
 * @get_groupname: Getter for the #GumDbusGroup:groupname property.
 * @get_grouptype: Getter for the #GumDbusGroup:grouptype property.
 * @get_secret: Getter for the #GumDbusGroup:secret property.
 * @unregistered: Handler for the #GumDbusGroup::unregistered signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-tizen-SecurityAccounts-gUserManagement-Group.top_of_page">org.tizen.SecurityAccounts.gUserManagement.Group</link>.
 */

static void
gum_dbus_group_default_init (GumDbusGroupIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * GumDbusGroup::handle-add-group:
   * @object: A #GumDbusGroup.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_preferred_gid: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-tizen-SecurityAccounts-gUserManagement-Group.addGroup">addGroup()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call gum_dbus_group_complete_add_group() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-add-group",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (GumDbusGroupIface, handle_add_group),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_UINT);

  /**
   * GumDbusGroup::handle-delete-group:
   * @object: A #GumDbusGroup.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-tizen-SecurityAccounts-gUserManagement-Group.deleteGroup">deleteGroup()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call gum_dbus_group_complete_delete_group() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-delete-group",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (GumDbusGroupIface, handle_delete_group),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * GumDbusGroup::handle-update-group:
   * @object: A #GumDbusGroup.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-tizen-SecurityAccounts-gUserManagement-Group.updateGroup">updateGroup()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call gum_dbus_group_complete_update_group() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-update-group",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (GumDbusGroupIface, handle_update_group),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * GumDbusGroup::handle-add-member:
   * @object: A #GumDbusGroup.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_uid: Argument passed by remote caller.
   * @arg_add_as_admin: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-tizen-SecurityAccounts-gUserManagement-Group.addMember">addMember()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call gum_dbus_group_complete_add_member() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-add-member",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (GumDbusGroupIface, handle_add_member),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    3,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_UINT, G_TYPE_BOOLEAN);

  /**
   * GumDbusGroup::handle-delete-member:
   * @object: A #GumDbusGroup.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_uid: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-tizen-SecurityAccounts-gUserManagement-Group.deleteMember">deleteMember()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call gum_dbus_group_complete_delete_member() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-delete-member",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (GumDbusGroupIface, handle_delete_member),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_UINT);

  /* GObject signals for received D-Bus signals: */
  /**
   * GumDbusGroup::unregistered:
   * @object: A #GumDbusGroup.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-tizen-SecurityAccounts-gUserManagement-Group.unregistered">"unregistered"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("unregistered",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (GumDbusGroupIface, unregistered),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    0);

  /* GObject properties for D-Bus properties: */
  /**
   * GumDbusGroup:grouptype:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-tizen-SecurityAccounts-gUserManagement-Group.grouptype">"grouptype"</link>.
   *
   * Since the D-Bus property for this #GObject property is both readable and writable, it is meaningful to both read from it and write to it on both the service- and client-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_uint ("grouptype", "grouptype", "grouptype", 0, G_MAXUINT16, 0, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * GumDbusGroup:gid:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-tizen-SecurityAccounts-gUserManagement-Group.gid">"gid"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_uint ("gid", "gid", "gid", 0, G_MAXUINT32, 0, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * GumDbusGroup:groupname:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-tizen-SecurityAccounts-gUserManagement-Group.groupname">"groupname"</link>.
   *
   * Since the D-Bus property for this #GObject property is both readable and writable, it is meaningful to both read from it and write to it on both the service- and client-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_string ("groupname", "groupname", "groupname", NULL, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * GumDbusGroup:secret:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-tizen-SecurityAccounts-gUserManagement-Group.secret">"secret"</link>.
   *
   * Since the D-Bus property for this #GObject property is both readable and writable, it is meaningful to both read from it and write to it on both the service- and client-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_string ("secret", "secret", "secret", NULL, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
}

typedef GumDbusGroupIface GumDbusGroupInterface;
G_DEFINE_INTERFACE (GumDbusGroup, gum_dbus_group, G_TYPE_OBJECT);

/**
 * gum_dbus_group_get_grouptype: (skip)
 * @object: A #GumDbusGroup.
 *
 * Gets the value of the <link linkend="gdbus-property-org-tizen-SecurityAccounts-gUserManagement-Group.grouptype">"grouptype"</link> D-Bus property.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
guint16 
gum_dbus_group_get_grouptype (GumDbusGroup *object)
{
  return GUM_DBUS_GROUP_GET_IFACE (object)->get_grouptype (object);
}

/**
 * gum_dbus_group_set_grouptype: (skip)
 * @object: A #GumDbusGroup.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-tizen-SecurityAccounts-gUserManagement-Group.grouptype">"grouptype"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 */
void
gum_dbus_group_set_grouptype (GumDbusGroup *object, guint16 value)
{
  g_object_set (G_OBJECT (object), "grouptype", value, NULL);
}

/**
 * gum_dbus_group_get_gid: (skip)
 * @object: A #GumDbusGroup.
 *
 * Gets the value of the <link linkend="gdbus-property-org-tizen-SecurityAccounts-gUserManagement-Group.gid">"gid"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
guint 
gum_dbus_group_get_gid (GumDbusGroup *object)
{
  return GUM_DBUS_GROUP_GET_IFACE (object)->get_gid (object);
}

/**
 * gum_dbus_group_set_gid: (skip)
 * @object: A #GumDbusGroup.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-tizen-SecurityAccounts-gUserManagement-Group.gid">"gid"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
gum_dbus_group_set_gid (GumDbusGroup *object, guint value)
{
  g_object_set (G_OBJECT (object), "gid", value, NULL);
}

/**
 * gum_dbus_group_get_groupname: (skip)
 * @object: A #GumDbusGroup.
 *
 * Gets the value of the <link linkend="gdbus-property-org-tizen-SecurityAccounts-gUserManagement-Group.groupname">"groupname"</link> D-Bus property.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 *
 * <warning>The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use gum_dbus_group_dup_groupname() if on another thread.</warning>
 *
 * Returns: (transfer none): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
const gchar *
gum_dbus_group_get_groupname (GumDbusGroup *object)
{
  return GUM_DBUS_GROUP_GET_IFACE (object)->get_groupname (object);
}

/**
 * gum_dbus_group_dup_groupname: (skip)
 * @object: A #GumDbusGroup.
 *
 * Gets a copy of the <link linkend="gdbus-property-org-tizen-SecurityAccounts-gUserManagement-Group.groupname">"groupname"</link> D-Bus property.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full): The property value or %NULL if the property is not set. The returned value should be freed with g_free().
 */
gchar *
gum_dbus_group_dup_groupname (GumDbusGroup *object)
{
  gchar *value;
  g_object_get (G_OBJECT (object), "groupname", &value, NULL);
  return value;
}

/**
 * gum_dbus_group_set_groupname: (skip)
 * @object: A #GumDbusGroup.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-tizen-SecurityAccounts-gUserManagement-Group.groupname">"groupname"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 */
void
gum_dbus_group_set_groupname (GumDbusGroup *object, const gchar *value)
{
  g_object_set (G_OBJECT (object), "groupname", value, NULL);
}

/**
 * gum_dbus_group_get_secret: (skip)
 * @object: A #GumDbusGroup.
 *
 * Gets the value of the <link linkend="gdbus-property-org-tizen-SecurityAccounts-gUserManagement-Group.secret">"secret"</link> D-Bus property.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 *
 * <warning>The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use gum_dbus_group_dup_secret() if on another thread.</warning>
 *
 * Returns: (transfer none): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
const gchar *
gum_dbus_group_get_secret (GumDbusGroup *object)
{
  return GUM_DBUS_GROUP_GET_IFACE (object)->get_secret (object);
}

/**
 * gum_dbus_group_dup_secret: (skip)
 * @object: A #GumDbusGroup.
 *
 * Gets a copy of the <link linkend="gdbus-property-org-tizen-SecurityAccounts-gUserManagement-Group.secret">"secret"</link> D-Bus property.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full): The property value or %NULL if the property is not set. The returned value should be freed with g_free().
 */
gchar *
gum_dbus_group_dup_secret (GumDbusGroup *object)
{
  gchar *value;
  g_object_get (G_OBJECT (object), "secret", &value, NULL);
  return value;
}

/**
 * gum_dbus_group_set_secret: (skip)
 * @object: A #GumDbusGroup.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-tizen-SecurityAccounts-gUserManagement-Group.secret">"secret"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 */
void
gum_dbus_group_set_secret (GumDbusGroup *object, const gchar *value)
{
  g_object_set (G_OBJECT (object), "secret", value, NULL);
}

/**
 * gum_dbus_group_emit_unregistered:
 * @object: A #GumDbusGroup.
 *
 * Emits the <link linkend="gdbus-signal-org-tizen-SecurityAccounts-gUserManagement-Group.unregistered">"unregistered"</link> D-Bus signal.
 */
void
gum_dbus_group_emit_unregistered (
    GumDbusGroup *object)
{
  g_signal_emit_by_name (object, "unregistered");
}

/**
 * gum_dbus_group_call_add_group:
 * @proxy: A #GumDbusGroupProxy.
 * @arg_preferred_gid: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-tizen-SecurityAccounts-gUserManagement-Group.addGroup">addGroup()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call gum_dbus_group_call_add_group_finish() to get the result of the operation.
 *
 * See gum_dbus_group_call_add_group_sync() for the synchronous, blocking version of this method.
 */
void
gum_dbus_group_call_add_group (
    GumDbusGroup *proxy,
    guint arg_preferred_gid,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "addGroup",
    g_variant_new ("(u)",
                   arg_preferred_gid),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * gum_dbus_group_call_add_group_finish:
 * @proxy: A #GumDbusGroupProxy.
 * @out_gid: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gum_dbus_group_call_add_group().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with gum_dbus_group_call_add_group().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
gum_dbus_group_call_add_group_finish (
    GumDbusGroup *proxy,
    guint *out_gid,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(u)",
                 out_gid);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * gum_dbus_group_call_add_group_sync:
 * @proxy: A #GumDbusGroupProxy.
 * @arg_preferred_gid: Argument to pass with the method invocation.
 * @out_gid: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-tizen-SecurityAccounts-gUserManagement-Group.addGroup">addGroup()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See gum_dbus_group_call_add_group() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
gum_dbus_group_call_add_group_sync (
    GumDbusGroup *proxy,
    guint arg_preferred_gid,
    guint *out_gid,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "addGroup",
    g_variant_new ("(u)",
                   arg_preferred_gid),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(u)",
                 out_gid);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * gum_dbus_group_call_delete_group:
 * @proxy: A #GumDbusGroupProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-tizen-SecurityAccounts-gUserManagement-Group.deleteGroup">deleteGroup()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call gum_dbus_group_call_delete_group_finish() to get the result of the operation.
 *
 * See gum_dbus_group_call_delete_group_sync() for the synchronous, blocking version of this method.
 */
void
gum_dbus_group_call_delete_group (
    GumDbusGroup *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "deleteGroup",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * gum_dbus_group_call_delete_group_finish:
 * @proxy: A #GumDbusGroupProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gum_dbus_group_call_delete_group().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with gum_dbus_group_call_delete_group().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
gum_dbus_group_call_delete_group_finish (
    GumDbusGroup *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * gum_dbus_group_call_delete_group_sync:
 * @proxy: A #GumDbusGroupProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-tizen-SecurityAccounts-gUserManagement-Group.deleteGroup">deleteGroup()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See gum_dbus_group_call_delete_group() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
gum_dbus_group_call_delete_group_sync (
    GumDbusGroup *proxy,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "deleteGroup",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * gum_dbus_group_call_update_group:
 * @proxy: A #GumDbusGroupProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-tizen-SecurityAccounts-gUserManagement-Group.updateGroup">updateGroup()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call gum_dbus_group_call_update_group_finish() to get the result of the operation.
 *
 * See gum_dbus_group_call_update_group_sync() for the synchronous, blocking version of this method.
 */
void
gum_dbus_group_call_update_group (
    GumDbusGroup *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "updateGroup",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * gum_dbus_group_call_update_group_finish:
 * @proxy: A #GumDbusGroupProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gum_dbus_group_call_update_group().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with gum_dbus_group_call_update_group().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
gum_dbus_group_call_update_group_finish (
    GumDbusGroup *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * gum_dbus_group_call_update_group_sync:
 * @proxy: A #GumDbusGroupProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-tizen-SecurityAccounts-gUserManagement-Group.updateGroup">updateGroup()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See gum_dbus_group_call_update_group() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
gum_dbus_group_call_update_group_sync (
    GumDbusGroup *proxy,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "updateGroup",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * gum_dbus_group_call_add_member:
 * @proxy: A #GumDbusGroupProxy.
 * @arg_uid: Argument to pass with the method invocation.
 * @arg_add_as_admin: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-tizen-SecurityAccounts-gUserManagement-Group.addMember">addMember()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call gum_dbus_group_call_add_member_finish() to get the result of the operation.
 *
 * See gum_dbus_group_call_add_member_sync() for the synchronous, blocking version of this method.
 */
void
gum_dbus_group_call_add_member (
    GumDbusGroup *proxy,
    guint arg_uid,
    gboolean arg_add_as_admin,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "addMember",
    g_variant_new ("(ub)",
                   arg_uid,
                   arg_add_as_admin),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * gum_dbus_group_call_add_member_finish:
 * @proxy: A #GumDbusGroupProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gum_dbus_group_call_add_member().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with gum_dbus_group_call_add_member().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
gum_dbus_group_call_add_member_finish (
    GumDbusGroup *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * gum_dbus_group_call_add_member_sync:
 * @proxy: A #GumDbusGroupProxy.
 * @arg_uid: Argument to pass with the method invocation.
 * @arg_add_as_admin: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-tizen-SecurityAccounts-gUserManagement-Group.addMember">addMember()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See gum_dbus_group_call_add_member() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
gum_dbus_group_call_add_member_sync (
    GumDbusGroup *proxy,
    guint arg_uid,
    gboolean arg_add_as_admin,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "addMember",
    g_variant_new ("(ub)",
                   arg_uid,
                   arg_add_as_admin),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * gum_dbus_group_call_delete_member:
 * @proxy: A #GumDbusGroupProxy.
 * @arg_uid: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-tizen-SecurityAccounts-gUserManagement-Group.deleteMember">deleteMember()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call gum_dbus_group_call_delete_member_finish() to get the result of the operation.
 *
 * See gum_dbus_group_call_delete_member_sync() for the synchronous, blocking version of this method.
 */
void
gum_dbus_group_call_delete_member (
    GumDbusGroup *proxy,
    guint arg_uid,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "deleteMember",
    g_variant_new ("(u)",
                   arg_uid),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * gum_dbus_group_call_delete_member_finish:
 * @proxy: A #GumDbusGroupProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gum_dbus_group_call_delete_member().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with gum_dbus_group_call_delete_member().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
gum_dbus_group_call_delete_member_finish (
    GumDbusGroup *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * gum_dbus_group_call_delete_member_sync:
 * @proxy: A #GumDbusGroupProxy.
 * @arg_uid: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-tizen-SecurityAccounts-gUserManagement-Group.deleteMember">deleteMember()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See gum_dbus_group_call_delete_member() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
gum_dbus_group_call_delete_member_sync (
    GumDbusGroup *proxy,
    guint arg_uid,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "deleteMember",
    g_variant_new ("(u)",
                   arg_uid),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * gum_dbus_group_complete_add_group:
 * @object: A #GumDbusGroup.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @gid: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-tizen-SecurityAccounts-gUserManagement-Group.addGroup">addGroup()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
gum_dbus_group_complete_add_group (
    GumDbusGroup *object,
    GDBusMethodInvocation *invocation,
    guint gid)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(u)",
                   gid));
}

/**
 * gum_dbus_group_complete_delete_group:
 * @object: A #GumDbusGroup.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-tizen-SecurityAccounts-gUserManagement-Group.deleteGroup">deleteGroup()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
gum_dbus_group_complete_delete_group (
    GumDbusGroup *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * gum_dbus_group_complete_update_group:
 * @object: A #GumDbusGroup.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-tizen-SecurityAccounts-gUserManagement-Group.updateGroup">updateGroup()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
gum_dbus_group_complete_update_group (
    GumDbusGroup *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * gum_dbus_group_complete_add_member:
 * @object: A #GumDbusGroup.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-tizen-SecurityAccounts-gUserManagement-Group.addMember">addMember()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
gum_dbus_group_complete_add_member (
    GumDbusGroup *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * gum_dbus_group_complete_delete_member:
 * @object: A #GumDbusGroup.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-tizen-SecurityAccounts-gUserManagement-Group.deleteMember">deleteMember()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
gum_dbus_group_complete_delete_member (
    GumDbusGroup *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/* ------------------------------------------------------------------------ */

/**
 * GumDbusGroupProxy:
 *
 * The #GumDbusGroupProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * GumDbusGroupProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #GumDbusGroupProxy.
 */

struct _GumDbusGroupProxyPrivate
{
  GData *qdata;
};

static void gum_dbus_group_proxy_iface_init (GumDbusGroupIface *iface);

G_DEFINE_TYPE_WITH_CODE (GumDbusGroupProxy, gum_dbus_group_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (GUM_DBUS_TYPE_GROUP, gum_dbus_group_proxy_iface_init));

static void
gum_dbus_group_proxy_finalize (GObject *object)
{
  GumDbusGroupProxy *proxy = GUM_DBUS_GROUP_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (gum_dbus_group_proxy_parent_class)->finalize (object);
}

static void
gum_dbus_group_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 4);
  info = _gum_dbus_group_property_info_pointers[prop_id - 1];
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (object), info->parent_struct.name);
  if (info->use_gvariant)
    {
      g_value_set_variant (value, variant);
    }
  else
    {
      if (variant != NULL)
        g_dbus_gvariant_to_gvalue (variant, value);
    }
  if (variant != NULL)
    g_variant_unref (variant);
}

static void
gum_dbus_group_proxy_set_property_cb (GDBusProxy *proxy,
  GAsyncResult *res,
  gpointer      user_data)
{
  const _ExtendedGDBusPropertyInfo *info = user_data;
  GError *error;
  error = NULL;
  if (!g_dbus_proxy_call_finish (proxy, res, &error))
    {
      g_warning ("Error setting property `%s' on interface org.tizen.SecurityAccounts.gUserManagement.Group: %s (%s, %d)",
                 info->parent_struct.name, 
                 error->message, g_quark_to_string (error->domain), error->code);
      g_error_free (error);
    }
}

static void
gum_dbus_group_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 4);
  info = _gum_dbus_group_property_info_pointers[prop_id - 1];
  variant = g_dbus_gvalue_to_gvariant (value, G_VARIANT_TYPE (info->parent_struct.signature));
  g_dbus_proxy_call (G_DBUS_PROXY (object),
    "org.freedesktop.DBus.Properties.Set",
    g_variant_new ("(ssv)", "org.tizen.SecurityAccounts.gUserManagement.Group", info->parent_struct.name, variant),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    NULL, (GAsyncReadyCallback) gum_dbus_group_proxy_set_property_cb, (gpointer) info);
  g_variant_unref (variant);
}

static void
gum_dbus_group_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_gum_dbus_group_interface_info, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], GUM_DBUS_TYPE_GROUP);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, GUM_DBUS_TYPE_GROUP);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
gum_dbus_group_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  GumDbusGroupProxy *proxy = GUM_DBUS_GROUP_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_gum_dbus_group_interface_info, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_gum_dbus_group_interface_info, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static guint16 
gum_dbus_group_proxy_get_grouptype (GumDbusGroup *object)
{
  GumDbusGroupProxy *proxy = GUM_DBUS_GROUP_PROXY (object);
  GVariant *variant;
  guint16 value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "grouptype");
  if (variant != NULL)
    {
      value = g_variant_get_uint16 (variant);
      g_variant_unref (variant);
    }
  return value;
}

static guint 
gum_dbus_group_proxy_get_gid (GumDbusGroup *object)
{
  GumDbusGroupProxy *proxy = GUM_DBUS_GROUP_PROXY (object);
  GVariant *variant;
  guint value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "gid");
  if (variant != NULL)
    {
      value = g_variant_get_uint32 (variant);
      g_variant_unref (variant);
    }
  return value;
}

static const gchar *
gum_dbus_group_proxy_get_groupname (GumDbusGroup *object)
{
  GumDbusGroupProxy *proxy = GUM_DBUS_GROUP_PROXY (object);
  GVariant *variant;
  const gchar *value = NULL;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "groupname");
  if (variant != NULL)
    {
      value = g_variant_get_string (variant, NULL);
      g_variant_unref (variant);
    }
  return value;
}

static const gchar *
gum_dbus_group_proxy_get_secret (GumDbusGroup *object)
{
  GumDbusGroupProxy *proxy = GUM_DBUS_GROUP_PROXY (object);
  GVariant *variant;
  const gchar *value = NULL;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "secret");
  if (variant != NULL)
    {
      value = g_variant_get_string (variant, NULL);
      g_variant_unref (variant);
    }
  return value;
}

static void
gum_dbus_group_proxy_init (GumDbusGroupProxy *proxy)
{
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, GUM_DBUS_TYPE_GROUP_PROXY, GumDbusGroupProxyPrivate);
  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), gum_dbus_group_interface_info ());
}

static void
gum_dbus_group_proxy_class_init (GumDbusGroupProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  g_type_class_add_private (klass, sizeof (GumDbusGroupProxyPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = gum_dbus_group_proxy_finalize;
  gobject_class->get_property = gum_dbus_group_proxy_get_property;
  gobject_class->set_property = gum_dbus_group_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = gum_dbus_group_proxy_g_signal;
  proxy_class->g_properties_changed = gum_dbus_group_proxy_g_properties_changed;


  gum_dbus_group_override_properties (gobject_class, 1);
}

static void
gum_dbus_group_proxy_iface_init (GumDbusGroupIface *iface)
{
  iface->get_grouptype = gum_dbus_group_proxy_get_grouptype;
  iface->get_gid = gum_dbus_group_proxy_get_gid;
  iface->get_groupname = gum_dbus_group_proxy_get_groupname;
  iface->get_secret = gum_dbus_group_proxy_get_secret;
}

/**
 * gum_dbus_group_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-tizen-SecurityAccounts-gUserManagement-Group.top_of_page">org.tizen.SecurityAccounts.gUserManagement.Group</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call gum_dbus_group_proxy_new_finish() to get the result of the operation.
 *
 * See gum_dbus_group_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
gum_dbus_group_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (GUM_DBUS_TYPE_GROUP_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.tizen.SecurityAccounts.gUserManagement.Group", NULL);
}

/**
 * gum_dbus_group_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gum_dbus_group_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with gum_dbus_group_proxy_new().
 *
 * Returns: (transfer full) (type GumDbusGroupProxy): The constructed proxy object or %NULL if @error is set.
 */
GumDbusGroup *
gum_dbus_group_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return GUM_DBUS_GROUP (ret);
  else
    return NULL;
}

/**
 * gum_dbus_group_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-tizen-SecurityAccounts-gUserManagement-Group.top_of_page">org.tizen.SecurityAccounts.gUserManagement.Group</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See gum_dbus_group_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type GumDbusGroupProxy): The constructed proxy object or %NULL if @error is set.
 */
GumDbusGroup *
gum_dbus_group_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (GUM_DBUS_TYPE_GROUP_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.tizen.SecurityAccounts.gUserManagement.Group", NULL);
  if (ret != NULL)
    return GUM_DBUS_GROUP (ret);
  else
    return NULL;
}


/**
 * gum_dbus_group_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like gum_dbus_group_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call gum_dbus_group_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See gum_dbus_group_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
gum_dbus_group_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (GUM_DBUS_TYPE_GROUP_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.tizen.SecurityAccounts.gUserManagement.Group", NULL);
}

/**
 * gum_dbus_group_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gum_dbus_group_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with gum_dbus_group_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type GumDbusGroupProxy): The constructed proxy object or %NULL if @error is set.
 */
GumDbusGroup *
gum_dbus_group_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return GUM_DBUS_GROUP (ret);
  else
    return NULL;
}

/**
 * gum_dbus_group_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like gum_dbus_group_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See gum_dbus_group_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type GumDbusGroupProxy): The constructed proxy object or %NULL if @error is set.
 */
GumDbusGroup *
gum_dbus_group_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (GUM_DBUS_TYPE_GROUP_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.tizen.SecurityAccounts.gUserManagement.Group", NULL);
  if (ret != NULL)
    return GUM_DBUS_GROUP (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * GumDbusGroupSkeleton:
 *
 * The #GumDbusGroupSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * GumDbusGroupSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #GumDbusGroupSkeleton.
 */

struct _GumDbusGroupSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_gum_dbus_group_skeleton_handle_method_call (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  GumDbusGroupSkeleton *skeleton = GUM_DBUS_GROUP_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], GUM_DBUS_TYPE_GROUP);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, GUM_DBUS_TYPE_GROUP);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_gum_dbus_group_skeleton_handle_get_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  GumDbusGroupSkeleton *skeleton = GUM_DBUS_GROUP_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_gum_dbus_group_interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_gum_dbus_group_skeleton_handle_set_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  GumDbusGroupSkeleton *skeleton = GUM_DBUS_GROUP_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_gum_dbus_group_interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _gum_dbus_group_skeleton_vtable =
{
  _gum_dbus_group_skeleton_handle_method_call,
  _gum_dbus_group_skeleton_handle_get_property,
  _gum_dbus_group_skeleton_handle_set_property
};

static GDBusInterfaceInfo *
gum_dbus_group_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton)
{
  return gum_dbus_group_interface_info ();
}

static GDBusInterfaceVTable *
gum_dbus_group_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton)
{
  return (GDBusInterfaceVTable *) &_gum_dbus_group_skeleton_vtable;
}

static GVariant *
gum_dbus_group_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  GumDbusGroupSkeleton *skeleton = GUM_DBUS_GROUP_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_gum_dbus_group_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _gum_dbus_group_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _gum_dbus_group_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _gum_dbus_group_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.tizen.SecurityAccounts.gUserManagement.Group", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static gboolean _gum_dbus_group_emit_changed (gpointer user_data);

static void
gum_dbus_group_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
  GumDbusGroupSkeleton *skeleton = GUM_DBUS_GROUP_SKELETON (_skeleton);
  gboolean emit_changed = FALSE;

  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    {
      g_source_destroy (skeleton->priv->changed_properties_idle_source);
      skeleton->priv->changed_properties_idle_source = NULL;
      emit_changed = TRUE;
    }
  g_mutex_unlock (&skeleton->priv->lock);

  if (emit_changed)
    _gum_dbus_group_emit_changed (skeleton);
}

static void
_gum_dbus_group_on_signal_unregistered (
    GumDbusGroup *object)
{
  GumDbusGroupSkeleton *skeleton = GUM_DBUS_GROUP_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("()"));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.tizen.SecurityAccounts.gUserManagement.Group", "unregistered",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void gum_dbus_group_skeleton_iface_init (GumDbusGroupIface *iface);
G_DEFINE_TYPE_WITH_CODE (GumDbusGroupSkeleton, gum_dbus_group_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (GUM_DBUS_TYPE_GROUP, gum_dbus_group_skeleton_iface_init));

static void
gum_dbus_group_skeleton_finalize (GObject *object)
{
  GumDbusGroupSkeleton *skeleton = GUM_DBUS_GROUP_SKELETON (object);
  guint n;
  for (n = 0; n < 4; n++)
    g_value_unset (&skeleton->priv->properties[n]);
  g_free (skeleton->priv->properties);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (gum_dbus_group_skeleton_parent_class)->finalize (object);
}

static void
gum_dbus_group_skeleton_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
  GumDbusGroupSkeleton *skeleton = GUM_DBUS_GROUP_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 4);
  g_mutex_lock (&skeleton->priv->lock);
  g_value_copy (&skeleton->priv->properties[prop_id - 1], value);
  g_mutex_unlock (&skeleton->priv->lock);
}

static gboolean
_gum_dbus_group_emit_changed (gpointer user_data)
{
  GumDbusGroupSkeleton *skeleton = GUM_DBUS_GROUP_SKELETON (user_data);
  GList *l;
  GVariantBuilder builder;
  GVariantBuilder invalidated_builder;
  guint num_changes;

  g_mutex_lock (&skeleton->priv->lock);
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  g_variant_builder_init (&invalidated_builder, G_VARIANT_TYPE ("as"));
  for (l = skeleton->priv->changed_properties, num_changes = 0; l != NULL; l = l->next)
    {
      ChangedProperty *cp = l->data;
      GVariant *variant;
      const GValue *cur_value;

      cur_value = &skeleton->priv->properties[cp->prop_id - 1];
      if (!_g_value_equal (cur_value, &cp->orig_value))
        {
          variant = g_dbus_gvalue_to_gvariant (cur_value, G_VARIANT_TYPE (cp->info->parent_struct.signature));
          g_variant_builder_add (&builder, "{sv}", cp->info->parent_struct.name, variant);
          g_variant_unref (variant);
          num_changes++;
        }
    }
  if (num_changes > 0)
    {
      GList *connections, *l;
      GVariant *signal_variant;
      signal_variant = g_variant_ref_sink (g_variant_new ("(sa{sv}as)", "org.tizen.SecurityAccounts.gUserManagement.Group",
                                           &builder, &invalidated_builder));
      connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));
      for (l = connections; l != NULL; l = l->next)
        {
          GDBusConnection *connection = l->data;

          g_dbus_connection_emit_signal (connection,
                                         NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)),
                                         "org.freedesktop.DBus.Properties",
                                         "PropertiesChanged",
                                         signal_variant,
                                         NULL);
        }
      g_variant_unref (signal_variant);
      g_list_free_full (connections, g_object_unref);
    }
  else
    {
      g_variant_builder_clear (&builder);
      g_variant_builder_clear (&invalidated_builder);
    }
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  skeleton->priv->changed_properties = NULL;
  skeleton->priv->changed_properties_idle_source = NULL;
  g_mutex_unlock (&skeleton->priv->lock);
  return FALSE;
}

static void
_gum_dbus_group_schedule_emit_changed (GumDbusGroupSkeleton *skeleton, const _ExtendedGDBusPropertyInfo *info, guint prop_id, const GValue *orig_value)
{
  ChangedProperty *cp;
  GList *l;
  cp = NULL;
  for (l = skeleton->priv->changed_properties; l != NULL; l = l->next)
    {
      ChangedProperty *i_cp = l->data;
      if (i_cp->info == info)
        {
          cp = i_cp;
          break;
        }
    }
  if (cp == NULL)
    {
      cp = g_new0 (ChangedProperty, 1);
      cp->prop_id = prop_id;
      cp->info = info;
      skeleton->priv->changed_properties = g_list_prepend (skeleton->priv->changed_properties, cp);
      g_value_init (&cp->orig_value, G_VALUE_TYPE (orig_value));
      g_value_copy (orig_value, &cp->orig_value);
    }
}

static void
gum_dbus_group_skeleton_notify (GObject      *object,
  GParamSpec *pspec)
{
  GumDbusGroupSkeleton *skeleton = GUM_DBUS_GROUP_SKELETON (object);
  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties != NULL &&
      skeleton->priv->changed_properties_idle_source == NULL)
    {
      skeleton->priv->changed_properties_idle_source = g_idle_source_new ();
      g_source_set_priority (skeleton->priv->changed_properties_idle_source, G_PRIORITY_DEFAULT);
      g_source_set_callback (skeleton->priv->changed_properties_idle_source, _gum_dbus_group_emit_changed, g_object_ref (skeleton), (GDestroyNotify) g_object_unref);
      g_source_attach (skeleton->priv->changed_properties_idle_source, skeleton->priv->context);
      g_source_unref (skeleton->priv->changed_properties_idle_source);
    }
  g_mutex_unlock (&skeleton->priv->lock);
}

static void
gum_dbus_group_skeleton_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  GumDbusGroupSkeleton *skeleton = GUM_DBUS_GROUP_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 4);
  g_mutex_lock (&skeleton->priv->lock);
  g_object_freeze_notify (object);
  if (!_g_value_equal (value, &skeleton->priv->properties[prop_id - 1]))
    {
      if (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)) != NULL)
        _gum_dbus_group_schedule_emit_changed (skeleton, _gum_dbus_group_property_info_pointers[prop_id - 1], prop_id, &skeleton->priv->properties[prop_id - 1]);
      g_value_copy (value, &skeleton->priv->properties[prop_id - 1]);
      g_object_notify_by_pspec (object, pspec);
    }
  g_mutex_unlock (&skeleton->priv->lock);
  g_object_thaw_notify (object);
}

static void
gum_dbus_group_skeleton_init (GumDbusGroupSkeleton *skeleton)
{
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, GUM_DBUS_TYPE_GROUP_SKELETON, GumDbusGroupSkeletonPrivate);
  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
  skeleton->priv->properties = g_new0 (GValue, 4);
  g_value_init (&skeleton->priv->properties[0], G_TYPE_UINT);
  g_value_init (&skeleton->priv->properties[1], G_TYPE_UINT);
  g_value_init (&skeleton->priv->properties[2], G_TYPE_STRING);
  g_value_init (&skeleton->priv->properties[3], G_TYPE_STRING);
}

static guint16 
gum_dbus_group_skeleton_get_grouptype (GumDbusGroup *object)
{
  GumDbusGroupSkeleton *skeleton = GUM_DBUS_GROUP_SKELETON (object);
  guint value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_uint (&(skeleton->priv->properties[0]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static guint 
gum_dbus_group_skeleton_get_gid (GumDbusGroup *object)
{
  GumDbusGroupSkeleton *skeleton = GUM_DBUS_GROUP_SKELETON (object);
  guint value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_uint (&(skeleton->priv->properties[1]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static const gchar *
gum_dbus_group_skeleton_get_groupname (GumDbusGroup *object)
{
  GumDbusGroupSkeleton *skeleton = GUM_DBUS_GROUP_SKELETON (object);
  const gchar *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_string (&(skeleton->priv->properties[2]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static const gchar *
gum_dbus_group_skeleton_get_secret (GumDbusGroup *object)
{
  GumDbusGroupSkeleton *skeleton = GUM_DBUS_GROUP_SKELETON (object);
  const gchar *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_string (&(skeleton->priv->properties[3]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static void
gum_dbus_group_skeleton_class_init (GumDbusGroupSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  g_type_class_add_private (klass, sizeof (GumDbusGroupSkeletonPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = gum_dbus_group_skeleton_finalize;
  gobject_class->get_property = gum_dbus_group_skeleton_get_property;
  gobject_class->set_property = gum_dbus_group_skeleton_set_property;
  gobject_class->notify       = gum_dbus_group_skeleton_notify;


  gum_dbus_group_override_properties (gobject_class, 1);

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = gum_dbus_group_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = gum_dbus_group_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = gum_dbus_group_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = gum_dbus_group_skeleton_dbus_interface_get_vtable;
}

static void
gum_dbus_group_skeleton_iface_init (GumDbusGroupIface *iface)
{
  iface->unregistered = _gum_dbus_group_on_signal_unregistered;
  iface->get_grouptype = gum_dbus_group_skeleton_get_grouptype;
  iface->get_gid = gum_dbus_group_skeleton_get_gid;
  iface->get_groupname = gum_dbus_group_skeleton_get_groupname;
  iface->get_secret = gum_dbus_group_skeleton_get_secret;
}

/**
 * gum_dbus_group_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-tizen-SecurityAccounts-gUserManagement-Group.top_of_page">org.tizen.SecurityAccounts.gUserManagement.Group</link>.
 *
 * Returns: (transfer full) (type GumDbusGroupSkeleton): The skeleton object.
 */
GumDbusGroup *
gum_dbus_group_skeleton_new (void)
{
  return GUM_DBUS_GROUP (g_object_new (GUM_DBUS_TYPE_GROUP_SKELETON, NULL));
}

